name: Move Issues and PRs to Project Board

on:
  issues:
    types: [opened, assigned, closed]
  pull_request:
    types: [opened, ready_for_review, closed]

jobs:
  move_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Move Issue/PR to GitHub Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/jesswillcode/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
